#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
This module is used to listen for Firepower syslog events, parse them, then place them in a RabbitMQ queue.
"""

import json
import os
import re
import socketserver

import pika

from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


class FirepowerSyslogHandler():
    """
    A class to parse Firepower syslog events.
    """

    __rabbit_mq_host = None

    def __init__(self):
        self.__rabbit_mq_host = os.getenv("RABBIT_MQ_HOST")

    def _parse_event(self, data):
        """
        Parse the data using regex to extract the pertinent Firepower data.
        """

        # A Regex string for parsing Firepower IPS events generated by the FMC
        regex_string = r"([a-zA-z]{3}\s*\d{1,2}\s\d{2}:\d{2}:\d{2}) (\S*) SFIMS: \[([0-9:]*)\] \"([^\"]*)\"\s*" \
                       r"\[Impact: ([^\]]*)\]?\s*From \"([^\"]*)\" at ([a-zA-Z]{3}\s[a-zA-Z]{3}\s*\d{1,2}\s\d{2}:\d{2}:\d{2}\s\d{4}\s\S*)\s*" \
                       r"\[Classification: ([^\]]*)\]?\s*\[Priority: ([^\]]*)\]\s\{([^\}]*)\} ([0-9.]*):?([0-9]*)?\s?\(?([^\)]*)\)?->([0-9.]*)" \
                       r":?([0-9]*)?\s*\(?([^\)]*)\)?"

        # Try to parse the event, if this fails None is returned
        parsed_event = re.search(regex_string, data, re.MULTILINE)

        # If we properly parsed the event, do stuff
        if parsed_event:

            # Store the parsed data into a dict
            event_json = {
                "product": "Firepower",
                "fmc_hostname": parsed_event.group(2),
                "snort_id": parsed_event.group(3),
                "snort_name": parsed_event.group(4),
                "event_name": parsed_event.group(4),
                "event_details": f"{parsed_event.group(8)} event {parsed_event.group(4)} was detected by '{parsed_event.group(6)}'.",
                "impact_level": parsed_event.group(5),
                "sensor_name": parsed_event.group(6),
                "timestamp": parsed_event.group(7),
                "classification": parsed_event.group(8),
                "priority": parsed_event.group(9),
                "protocol": parsed_event.group(10),
                "src_ip": parsed_event.group(11),
                "src_port": parsed_event.group(12),
                "src_geo": parsed_event.group(13),
                "dst_ip": parsed_event.group(14),
                "dst_port": parsed_event.group(15),
                "dst_geo": parsed_event.group(16),
            }

            return event_json

        else:
            return None

    def _queue_event(self, event_json):
        """
        Place the parsed event on a RabbitMQ queue.
        """

        # Create RabbitMQ connection parameters
        connection_parameters = pika.ConnectionParameters(host=self.__rabbit_mq_host)

        # Build the RabbitMQ connection
        connection = pika.BlockingConnection(connection_parameters)

        # Get a channel for the RabbitMQ connection
        channel = connection.channel()

        # Declare a new queue for events
        channel.queue_declare(queue="events")

        # Publish the event to RabbitMQ
        channel.basic_publish(exchange="", routing_key="events", body=json.dumps(event_json))

        print(f"Event publiished to queue.  Event details:\n{json.dumps(event_json, indent=4)}")

        # Close the connection
        connection.close()


class SyslogHandler(socketserver.BaseRequestHandler):
    """
    The RequestHandler class for Command Center Syslog events.
    """

    def handle(self):
        """
        Handle when a packet is received on the socket.
        """

        self.data = bytes.decode(self.request[0].strip())
        self.socket = self.request[1]

        print(f"{self.client_address[0]} sent the following: {self.data}")

        event_parser = FirepowerSyslogHandler()

        # Try to parse the event data
        event_json = event_parser._parse_event(self.data)

        # If the event was parsed
        if event_json:

            # Store the event
            event_parser._queue_event(event_json)


if __name__ == "__main__":

    try:

        syslog_port = int(os.getenv("SYSLOG_PORT"))

        server = socketserver.UDPServer(("0.0.0.0", syslog_port), SyslogHandler)
        print(f"Server listening on port {syslog_port}...")
        server.serve_forever()
    except (IOError, SystemExit):
        raise
    except KeyboardInterrupt:
        print("\nCrtl+C Pressed. Shutting down.")
